services:
    # 🌐 Web API
    - type: web
      name: strava-backend
      env: python
      plan: free
      rootDir: backend
      buildCommand: "pip install -r requirements.txt"
      startCommand: "gunicorn app:app"
      envVars:
          - key: PYTHON_VERSION
            value: 3.11
          - key: STRAVA_CLIENT_ID
            sync: false
          - key: STRAVA_CLIENT_SECRET
            sync: false
          - key: STRAVA_REFRESH_TOKEN
            sync: false
          - key: STRAVA_ACCESS_TOKEN
            sync: false

    # 🕒 Worker (dagelijks script)
    - type: worker
      name: strava-daily-fetcher
      env: python
      plan: free
      rootDir: backend
      buildCommand: "pip install -r requirements.txt"
      startCommand: "python scripts/fetch_strava.py"
      schedule: "0 3 * * *"
      disk:
          name: strava-data
          mountPath: /opt/render/project/src/backend/data
          sizeGB: 1
